# 04 - Access the free economic database DBnomics with R ----
# URL: https://macro.cepremap.fr/article/2020-10/rdbnomics-tutorial/
library(rdbnomics)
library(tidyverse)
library(kableExtra)
library(RColorBrewer)
source("R/utils.R")
palette(brewer.pal(n = 9, name = "Dark2"))
fig_path <- "figures/04_rdbnomics-tutorial/"
# DBnomics, the world's economic database: https://db.nomics.world/
# The `rdbnomics` R package is available on:
# - CRAN: https://cran.r-project.org/package=rdbnomics
# - GitHub: https://github.com/dbnomics/rdbnomics
# - GitLab: https://git.nomics.world/dbnomics/rdbnomics

## Fetch time series by `ids` ----
# Assume you know which series you want to download.
# Every series identifier (`ids`) has three values
# that uniquely identify each time series in the data base.

# The format is: `provider_code/dataset_code/series_code`

### Fetch one series ----
# Fetch one series of the dataset "Unemployment rate" (ZUTN) 
# from the provider "AMECO"

# Providers on DBnomics: https://db.nomics.world/providers
# AMECO is the Annual Macro-ECOnomic database of the European Commission's 
# Directorate General for Economic and Financial Affairs

# ZUTN is the Unemployment rate: total: - Member States: definition EUROSTAT

# EA19 means we want the 19 European member states
df <- rdb(ids = "AMECO/ZUTN/EA19.1.0.0.0.ZUTN") |> 
  filter(!is.na(value)) |> 
  as_tibble()

colnames(df)
# At least ten columns are in the returned data frame
#   - @frequency (harmonized frequency generated by DBnomics)
#   - provider_code
#   - dataset_code
#   - series_code
#   - series_name
#   - original_period (character string)
#   - period (date of the first day of original_period)
#   - original_value (character string)
#   - value

reorder_cols(df)
# Other columns depend on the provider and the dataset.
# They always come in pairs (for the code and the name).

# Our data frame has:
#   - unit (code) and Unit (name)
#   - geo (code) and Country (name)
#   - freq (code) and Frequency (name)
df |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("01_AMECO_ZUTN_EA19.png", path = fig_path, height = 12, width = 24)
graphics.off()

### Fetch two series -----
# Fetch two series of the dataset "Unemployment rate" (ZUTN) 
# from the provider "AMECO"
df <- rdb(ids = c("AMECO/ZUTN/EA19.1.0.0.0.ZUTN", "AMECO/ZUTN/DNK.1.0.0.0.ZUTN")) |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("02_AMECO_ZUTN_EA19-DNK.png", path = fig_path, height = 12, width = 24)
graphics.off()

### Fetch two series from different datasets and different providers -----
df <- rdb(ids = c("AMECO/ZUTN/EA19.1.0.0.0.ZUTN", "Eurostat/une_rt_q/Q.SA.Y15-74.PC_ACT.T.EA19")) |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("03_AMECO_ZUTN_EA19-Eurostat_une.png", path = fig_path, height = 12, width = 24)
graphics.off()

## Fetch time series by `mask` ----
### Fetch one series ----
# One series of the dataset "Balance of Payments" (BOP) from the provider "IMF"
df <- rdb("IMF", "BOP", mask = "A.FR.BCA_BP6_EUR") |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("04_IMF_BOP_FR.png", path = fig_path, height = 12, width = 24)
graphics.off()

### Fetch two series ----
# Fetch two series of the dataset "Balance of Payments" (BOP) 
# from the provider "IMF"
df <- rdb("IMF", "BOP", mask = "A.FR+DE.BCA_BP6_EUR") |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  arrange(series_code, period) |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("05_IMF_BOP_FR-DE.png", path = fig_path, height = 12, width = 24)
graphics.off()

### Fetch all series along one dimension ----
# Fetch all series of the dataset "Balance of Payments" (BOP) 
# from the provider "IMF"
df <- rdb("IMF", "BOP", mask = "A..BCA_BP6_EUR") |> 
  filter(!is.na(value)) |> 
  arrange(desc(period), REF_AREA) |> 
  as_tibble() |> 
  head(n = 100)

df |> 
  reorder_cols() |> 
  display_table()

df |> 
  select(REF_AREA) |> 
  pull(REF_AREA) |> 
  unique()

### Fetch series along multiple dimensions ----
# Fetch series along multiple dimensions of the dataset "Balance of Payments" (BOP) 
# from the provider "IMF".
df <- rdb("IMF", "BOP", mask = "A.FR+DE.BCA_BP6_EUR+IA_BP6_EUR") |> 
  filter(!is.na(value)) |> 
  group_by(INDICATOR) |> 
  as_tibble() |> 
  top_n(n = 50, wt = period)

df |> 
  reorder_cols() |> 
  display_table()

## Fetch time series by `dimensions` ----
# Searching by `dimensions` is a less concise way of selecting time series than
# using the code in `mask`, but it works for all providers.

# There is a "Description of series code" at the bottom of every
# dataset page on the DBnomics website https://db.nomics.world/

### Fetch one value of one dimension of ZUTN from AMECO ----
df <- rdb("AMECO", "ZUTN", dimensions = list(geo = "ea19")) |> 
  filter(!is.na(value)) |> 
  as_tibble()

# Alternatively, try
df <- rdb(
  provider_code = "AMECO",
  dataset_code  = "ZUTN",
  dimensions = '{"geo":["ea19"]}'
  ) |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("06_AMECO_ZUTN_EA19.png", path = fig_path, height = 12, width = 24)
graphics.off()

### Fetch two values of one dimension of ZUTN from AMECO ----
df <- rdb("AMECO", "ZUTN", dimensions = list(geo = c("ea19", "dnk"))) |> 
  filter(!is.na(value)) |> 
  as_tibble()

# Alternatively, try
df <- rdb(
  provider_code = "AMECO",
  dataset_code  = "ZUTN",
  dimensions = '{"geo":["ea19","dnk"]}'
  ) |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  arrange(series_code, period) |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("07_AMECO_ZUTN_EA19-DNK.png", path = fig_path, height = 12, width = 24)
graphics.off()

### Fetch several values of several dimensions from Doing Business (DB) from World Bank ----
# Note: The World Bank Ease of Doing Business Index 
# is not published anymore due to manipulation
# on the side of the responsible economists.

## Fetch times series with a `query` ----
# The query is a Google-like search that will filter/select
# time series from a provider's data set.

### Fetch one series of dataset "WEO by countries" (WEO) from provider IMF ----
df <- rdb("IMF", "WEO:latest", query = "France current account balance percent") |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  arrange(series_name, period) |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("08_IMF_WEO_FR.png", path = fig_path, height = 12, width = 24)
graphics.off()

### Fetch series of dataset "WEO by countries" (WEO) from provider IMF ----
df <- rdb("IMF", "WEO:2010-04", query = "current account balance percent") |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  arrange(series_name, period) |> 
  reorder_cols() |> 
  as_tibble() |> 
  head() |> 
  display_table()

## Fetch time series found on the web site ----
# When you don't know the codes of the dimensions, the provider,
# the dataset or series name, you can always:
#   - go to the page of a dataset on the DBnomics website
#   https://db.nomics.world/
#   - select some dimension by using the input widgets of the left column,
#   - click on "Copy API link" in the drop-down menu of the "Download" button,
#   - use the `rdbnomics::rdb(api_link = ...)` function such as below.
df <- rdb(api_link = "https://api.db.nomics.world/v22/series/SECO/qna_e_csa/gdp-tbgs.defl.L.Q?observations=1") |> 
  filter(!is.na(value)) |> 
  as_tibble()

df |> 
  arrange(period, series_name) |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("09_SECO_GDP_GR.png", path = fig_path, height = 12, width = 24)
graphics.off()

## Fetch time series from the cart ----
# On the cart page of the DBnomics website https://db.nomics.world/
# click on "Copy API link" and copy-paste it as the argument of the
# `rdbnomics::rdb(api_link = ...)` function.

# When you update your card, you have to copy this link again, 
# because the link itself contains the `ids` of the series in the cart.
df <- rdb(api_link = "https://api.db.nomics.world/v22/series?observations=1&series_ids=BOE/6008/RPMTDDC,BOE/6231/RPMTBVE") |> 
  filter(!is.na(value)) |> 
  as_tibble()

df <- df |>  
  mutate(
    series_name = sapply(
      X = series_name,
      FUN = function(y) {
        paste0(
          paste0(
            strsplit(y, split = "institutions' ")[[1]],
            collapse = "institutions'\n"
          ),
          "\n"
        )
      }
    )
  )

df |> 
  arrange(period, series_name) |> 
  reorder_cols() |> 
  display_table()

ggplot(df, aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("10_BOE_RPMTDDC-RPMTBVE.png", path = fig_path, height = 12, width = 24)
graphics.off()

## Fetch the available datasets from a provider ---
# When fetching series from DBnomics at https://db.nomics.world/
# you need to give a provider of a dataset before specifying the correct dimensions.
# Download the list of all available datasets for a provider.
# with the function `dbnomics::rdb_datasets()`

# To fetch the IMF datasets, use
DT <- rdb_datasets(provider_code = "IMF")
display_table(DT[[1]])

# The function returns a named list (the list name is IMF) with
# one element that is of class `data.table`.

# The same function can fetch the available datasets of two providers
DT <- rdb_datasets(provider_code = c("IMF", "BDF"))
DT <- sapply(X = DT, FUN = function(y) { paste0(": ", nrow(y)) })
DT <- paste0("Number of datasets for ", names(DT), " ", unname(DT))
cat(DT, sep = "\n")

# In the event that you only request the datasets from a single provider,
# define `simplify = TRUE` to receive the result as 
# an object of class `data.table` instead of a list.
DT <- rdb_datasets(provider_code = "IMF", simplify = TRUE)
DT |> display_table()

# The extent of all datasets gathered by DBnomics
# can be appreciated by calling `rdbnomics::rdb_datasets()`
# with the argument `provider_code` set to `NULL` (default)
DT <- rdb_datasets(provider_code = NULL)

DT <- sapply(X = DT, FUN = function(y) { nrow(y) })
DT <- tibble(name = names(DT), n = unname(DT))
DT |> arrange(desc(n))

# Fetch the possible dimensions of available datasets from a provider ----

# When fetching series from DBnomics, it can be interesting and useful to specify
# the dimensions for a particular dataset to download only the series
# you want to analyze.

# With the function `rdbnomics::rdb_dimensions()`, you can
# download these dimensions along with their description.

# For the WEO dataset from the IMF, use
DT <- rdb_dimensions(
  provider_code = "IMF", 
  dataset_code  = "WEO:latest"
  )

# The result is a nested named list, with the names
# IMF, WEO, and the dimension names.
# At the end of each branch is an object of class `data.table`
DT_IMF_WEO <- DT$IMF$`WEO:latest`
DTnb <- paste0("Number of dimensions for IMF/WEO:latest : ", length(DT_IMF_WEO))
cat(DTnb, sep = "\n")
# Number of dimensions for IMF/WEO:latest : 3


# The different values of the first dimension of IMF/WEO are:
display_table(DT_IMF_WEO[[1]])

# In the event that you only request the dimensions of a dataset
# from a single provider, set `simplify = TRUE`
# so that the result is returned as a named list instead
# of a *nested* named list.
DT <- rdb_dimensions(
  provider_code = "IMF",
  dataset_code  = "WEO:latest",
  simplify = TRUE
  )

display_table(DT[[1]])

# You can measure the vast extent of datasets gathered by
# DBnomics by downloading all the possible dimensions.

# Set both `provider_code` and `dataset_code` to the default `NULL` values.
# rdb_dimensions(provider_code = NULL, dataset_code = NULL)

# Note: This will take even longer than simply fetching the
# names of the datasets.


## Fetch the series codes and names of available datasets from a provider ----
# You can download the list of series, and especially their
# codes, by specifying a provider inside the function
# `rdbnomics::rdb_series()`.

# The result is returned as a nested named list with an 
# object of class `data.table` at the end of each branch.

# Define `simplify = TRUE` to return the result as a `data.table`
# instead of a nested named list.

# For the provider IMF and the dataset WEO, the command is
rdb_series(
  provider_code = "IMF", 
  dataset_code  = "WEO:latest", 
  simplify = TRUE
  ) |>
  head() |>
  display_table()

# You can add features such as the specific `dimensions`
rdb_series(
  provider_code = "IMF", 
  dataset_code  = "WEO:latest", 
  dimensions = list(
    `weo-subject` = "NGDP_RPCH"
    ), 
  simplify = TRUE
  ) |> 
  display_table()

# Use this function parsimoniously since the amount of
# series per dataset and provider can be very large.


## Proxy configuration or connection error `Could not resolve host` ----
# When using the function `rdbnomics::rdb()`, you may come across
# the error
# Error in open.connection(con, "rb") : 
#   Could not resolve host: api.db.nomics.world

# To get around this situation, you have two options:

#   1. configure `curl` to use a specific and authorized proxy.
#   2. Use the default R internet connection, i.e. the Internet Explorer
#    proxy defined in `internet2.dll`.


### Configure `curl` to use specific and authorized proxy ----
# In `rdbnomics`, by default the function `curl::curl_fetch_memory()`
# is used to fetch data.

# If a specific proxy must be used, it is possible to define it
# permanently with the package option
# `rdbnomics.curl_config` or on the fly through the argument `curl_config`.

# Because the object is a named list, its elements are paseed
# to the connection (the `curl_handle` objec created
# internally with `new_handle()`) with handle_setopt()
# before using `curl::curl_fetch_memory()`.

# To see the available parameters, run
names(curl::curl_options())
# or visit the website
# https://curl.haxx.se/libcurl/c/curl_easy_setopt.html

# Once they are chosen, you define the curl object as follows:
if (FALSE) {
  #### Set the connection up for a session ----
  # The `curl` connection can be set up for a specific session only
  # by modifying the package option
  options(rdbnomics.curl_config = h)
  
  # When fetching the data, the following command is executed internally
  hndl <- curl::new_handle()
  curl::handle_setopt(handle = hndl, .list = getOption("rdbnomics.curl_config"))
  curl::curl_fetch_memory(url = ..., handle = hndl)
  
  # After configuration, just use the standard functions of
  # `rdbnomics` such as
  df1 <- rdb(ids = "AMECO/ZUTN/EA19.1.0.0.0.ZUTN")
  
  # This option of the package can be disabled with:
  options(rdbnomics.curl = NULL)
  
  #### Use the connection only for a function call ----
  # If a complete configuration is not needed but just
  # an "on the fly" execution, then use the argument 
  # `curl_config` inside of the function `rdbnomics::rdb()`
  df1 <- rdb(ids = "AMECO/ZUTN/EA19.1.0.0.0.ZUTN", curl_config = h)
  
  ### Use the default R internet connection ----
  # To retrieve the data with the default R internet connection,
  # `rdbnomics` will use the `base::readLines()` function. 
  
  #### Set the connection up for a session ----
  # To activate this feature for a single session only, enable
  # the package option `rdbnomics.use_readLines`
  options(rdbnomics.use_readLines = TRUE)
  
  # Then use standard functions
  df1 <- rdb(ids = "AMECO/ZUTN/EA19.1.0.0.0.ZUTN")
  
  # And disable this configuration with
  options(rdbnomics.use_readLines = FALSE)
  
  
  #### Use the connection only for a function call ----
  # If you just want to do this once, use the argument `use_readLiens`
  # inside the function `rdbnomics::rdb()`
  df1 <- rdb(ids = "AMECO/ZUTN/EA19.1.0.0.0.ZUTN", use_readLines = TRUE)
}


## Transform time series with filters ----
# The `rdbnomics` R package interacts with the Time Series Editor of the
# DBnomics API to transform time series by applying filters to them.

# Available filters are listed on the DBnomics filters page
# https://editor.nomics.world/filters

# An example of how to proceed to interpolate two annual time series
# to monthly frequency with a spine interpolation
filters <- list(
  code = "interpolate",
  parameters = list(
    frequency = "monthly", 
    method = "spline"
    )
  )

# The request is
df <- rdb(
  ids = c("AMECO/ZUTN/EA19.1.0.0.0.ZUTN"),
  filters = filters
)

# If you want to apply more than one filter, the `filters` argument
# must be a list of valid filters
filters <- list(
  
  list(
    code = "interpolate",
    parameters = list(
      frequency = "monthly",
      method    = "spline"
    )
  ),
  
  list(
    code = "aggregate",
    parameters = list(
      frequency = "bi-annual",
      method    = "end_of_period"
    )
  )
)

df <- rdb(
  ids = c("AMECO/ZUTN/EA19.1.0.0.0.ZUTN", "AMECO/ZUTN/DNK.1.0.0.0.ZUTN"),
  filters = filters
)

# Note that when filters are used, the columns of the returned
# `data.table` object change.
# The new columns are:
#   - `period_middle_day`: The middle day of `original_period`
#     can be used to compare the interpolated and the original series graphically.
#   - `filtered` (boolean): `TRUE` if filtered, `FALSE` otherwise.

# The content of two columns are modified:
#   - `series_code`: same as before, but the suffix `_filtered` is added.
#   - `series_name`: same as before, but the suffix `(filtered)` is added.
df |> 
  head() |> 
  display_table()

df <- df[order(filtered, series_name, period)]
df <- reorder_cols(df)
display_table(head(df))

ggplot(df[!is.na(value)], aes(period, value, color = series_name)) +
  geom_line(lwd = 1.2) +
  geom_point(size = 2) +
  dbnomics()

ggsave("11_AMECO_ZUTN_EA19-DNK_filtered.png", path = fig_path, height = 12, width = 24)
graphics.off()
# END